# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 531, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.LineGamma1 = QtWidgets.QLineEdit(self.tab1)
        self.LineGamma1.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.LineGamma1.setObjectName("LineGamma1")
        self.LineGamma2 = QtWidgets.QLineEdit(self.tab1)
        self.LineGamma2.setGeometry(QtCore.QRect(240, 30, 113, 20))
        self.LineGamma2.setObjectName("LineGamma2")
        self.LineGamma3 = QtWidgets.QLineEdit(self.tab1)
        self.LineGamma3.setGeometry(QtCore.QRect(400, 30, 113, 20))
        self.LineGamma3.setObjectName("LineGamma3")
        self.EncryptButton = QtWidgets.QPushButton(self.tab1)
        self.EncryptButton.setGeometry(QtCore.QRect(0, 160, 75, 23))
        self.EncryptButton.setObjectName("EncryptButton")
        self.LabelGamma1 = QtWidgets.QLabel(self.tab1)
        self.LabelGamma1.setGeometry(QtCore.QRect(120, 10, 47, 13))
        self.LabelGamma1.setObjectName("LabelGamma1")
        self.LabelGamma2 = QtWidgets.QLabel(self.tab1)
        self.LabelGamma2.setGeometry(QtCore.QRect(270, 10, 47, 13))
        self.LabelGamma2.setObjectName("LabelGamma2")
        self.LabelGamma3 = QtWidgets.QLabel(self.tab1)
        self.LabelGamma3.setGeometry(QtCore.QRect(430, 10, 47, 13))
        self.LabelGamma3.setObjectName("LabelGamma3")
        self.LabelMessage = QtWidgets.QLabel(self.tab1)
        self.LabelMessage.setGeometry(QtCore.QRect(270, 60, 47, 13))
        self.LabelMessage.setObjectName("LabelMessage")
        self.LabelCiphergramm = QtWidgets.QLabel(self.tab1)
        self.LabelCiphergramm.setGeometry(QtCore.QRect(260, 170, 71, 16))
        self.LabelCiphergramm.setObjectName("LabelCiphergramm")
        self.Ciphergramm = QtWidgets.QTextEdit(self.tab1)
        self.Ciphergramm.setGeometry(QtCore.QRect(90, 190, 421, 101))
        self.Ciphergramm.setMouseTracking(False)
        self.Ciphergramm.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Ciphergramm.setReadOnly(True)
        self.Ciphergramm.setObjectName("Ciphergramm")
        self.Message = QtWidgets.QTextEdit(self.tab1)
        self.Message.setGeometry(QtCore.QRect(90, 80, 421, 81))
        self.Message.setTabChangesFocus(True)
        self.Message.setObjectName("Message")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.DecryptButton = QtWidgets.QPushButton(self.tab2)
        self.DecryptButton.setGeometry(QtCore.QRect(0, 160, 75, 23))
        self.DecryptButton.setObjectName("DecryptButton")
        self.LabelGamma12 = QtWidgets.QLabel(self.tab2)
        self.LabelGamma12.setGeometry(QtCore.QRect(120, 10, 47, 13))
        self.LabelGamma12.setObjectName("LabelGamma12")
        self.LineGamma32 = QtWidgets.QLineEdit(self.tab2)
        self.LineGamma32.setGeometry(QtCore.QRect(400, 30, 113, 20))
        self.LineGamma32.setObjectName("LineGamma32")
        self.LineGamma12 = QtWidgets.QLineEdit(self.tab2)
        self.LineGamma12.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.LineGamma12.setObjectName("LineGamma12")
        self.LabelGamma32 = QtWidgets.QLabel(self.tab2)
        self.LabelGamma32.setGeometry(QtCore.QRect(430, 10, 47, 13))
        self.LabelGamma32.setObjectName("LabelGamma32")
        self.LineGamma22 = QtWidgets.QLineEdit(self.tab2)
        self.LineGamma22.setGeometry(QtCore.QRect(240, 30, 113, 20))
        self.LineGamma22.setObjectName("LineGamma22")
        self.LabelGamma22 = QtWidgets.QLabel(self.tab2)
        self.LabelGamma22.setGeometry(QtCore.QRect(270, 10, 47, 13))
        self.LabelGamma22.setObjectName("LabelGamma22")
        self.LabelMessage2 = QtWidgets.QLabel(self.tab2)
        self.LabelMessage2.setGeometry(QtCore.QRect(270, 170, 47, 13))
        self.LabelMessage2.setObjectName("LabelMessage2")
        self.LabelCiphergramm2 = QtWidgets.QLabel(self.tab2)
        self.LabelCiphergramm2.setGeometry(QtCore.QRect(260, 60, 71, 16))
        self.LabelCiphergramm2.setObjectName("LabelCiphergramm2")
        self.Ciphergramm2 = QtWidgets.QTextEdit(self.tab2)
        self.Ciphergramm2.setGeometry(QtCore.QRect(90, 80, 421, 81))
        self.Ciphergramm2.setTabChangesFocus(True)
        self.Ciphergramm2.setObjectName("Ciphergramm2")
        self.Message2 = QtWidgets.QTextEdit(self.tab2)
        self.Message2.setGeometry(QtCore.QRect(90, 190, 421, 101))
        self.Message2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Message2.setReadOnly(True)
        self.Message2.setObjectName("Message2")
        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LineGamma1, self.LineGamma2)
        MainWindow.setTabOrder(self.LineGamma2, self.LineGamma3)
        MainWindow.setTabOrder(self.LineGamma3, self.Message)
        MainWindow.setTabOrder(self.Message, self.EncryptButton)
        MainWindow.setTabOrder(self.EncryptButton, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.LineGamma12)
        MainWindow.setTabOrder(self.LineGamma12, self.LineGamma22)
        MainWindow.setTabOrder(self.LineGamma22, self.LineGamma32)
        MainWindow.setTabOrder(self.LineGamma32, self.Ciphergramm2)
        MainWindow.setTabOrder(self.Ciphergramm2, self.DecryptButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gamming"))
        self.EncryptButton.setText(_translate("MainWindow", "Encrypt"))
        self.LabelGamma1.setText(_translate("MainWindow", "Gamma 1"))
        self.LabelGamma2.setText(_translate("MainWindow", "Gamma 2"))
        self.LabelGamma3.setText(_translate("MainWindow", "Gamma3"))
        self.LabelMessage.setText(_translate("MainWindow", "Message"))
        self.LabelCiphergramm.setText(_translate("MainWindow", "Ciphergramm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Encryption"))
        self.DecryptButton.setText(_translate("MainWindow", "Decrypt"))
        self.LabelGamma12.setText(_translate("MainWindow", "Gamma 1"))
        self.LabelGamma32.setText(_translate("MainWindow", "Gamma3"))
        self.LabelGamma22.setText(_translate("MainWindow", "Gamma 2"))
        self.LabelMessage2.setText(_translate("MainWindow", "Message"))
        self.LabelCiphergramm2.setText(_translate("MainWindow", "Ciphergramm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Decryption"))
